apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  source:
    chart: jupyterhub
    repoURL: https://hub.jupyter.org/helm-chart/
    targetRevision: 4.0.0
    helm:
      valuesObject:
        singleuser:
          storage:
            capacity: 256Mi
            dynamic:
              storageClass: longhorn
        cull:
          enabled: true
          timeout: 180
          every: 60
        prePuller:
          hook:
            enabled: false
          continuous:
            enabled: false
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - jupyterhub.k8s.libator.net
        scheduling:
          userScheduler:
            enabled: true
            replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jupyterhub
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # create destination kubernetes namespace
      - ServerSideApply=true # fix for meta data annotation being too long
    automated:
      selfHeal: true # auto sync and repair
      prune: false # delete ressources after deletion of this manifest
