apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  source:
    chart: jupyterhub
    repoURL: https://hub.jupyter.org/helm-chart/
    targetRevision: 4.0.0
    helm:
      valuesObject:
        singleuser:
          storage:
            capacity: 256Mi
            dynamic:
              storageClass: longhorn
        cull:
          enabled: true
          timeout: 180
          every: 60
        prePuller:
          hook:
            enabled: false
          continuous:
            enabled: false
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - jupyterhub.k8s.libator.net
        scheduling:
          userScheduler:
            enabled: true
            replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jupyterhub
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: false
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /metadata/labels/app.kubernetes.io/managed-by
      jmesPath: "[?app.kubernetes.io/managed-by=='kubespawner']"
