apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
spec:
  project: default
  source:
    chart: trino
    repoURL: https://trinodb.github.io/charts
    targetRevision: 1.35.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: traefik
          traefik.ingress.kubernetes.io/router.middlewares: traefik-x-forwarded-proto-https@kubernetescrd
          hosts:
            - host: trino.k8s.libator.net
              paths:
                - path: /
                  pathType: Prefix
        additionalConfigProperties:
          - http-server.process-forwarded=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: trino
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
